### ISSUE TITLE
The content or EmbeddedResource (js, css, assets) not reloading the changes without rebuilding the project.

### ISSUE THREAD

**Issue by irowbin** [ExtCore/ExtCore#71] opened 2017-07-05 09:56 UTC
Is this an issue or not? Cleaned up the cache and cookies from the browser, but the extension project aren't reloading the changed resources without re-building the project, such as the JavaScript file. I guess the js or css file has no concern with MS build system. 

I've added static file to my extension project **extension.csproj**  as Embedded resource like this but why we need to build each time when any  changes of CSS rules or JS variables has been defined? 
```javascript
 <EmbeddedResource Include="Views\**; assets\**;" />
 <Content Include="assets\**" />
```

**Comment by DmitrySikorsky** [comment] 2017-07-05 10:11
ExtCore takes the resources from assembly resources. So to update them you have to rebuild the assembly (in this case the updated resources will be rebuilt and embedded into the assembly again). So this is how it works. But we could make development easier by adding physical project locations to the resources discovery while development to avoid need to rebuild all projects with the resources every time they are changed.

**Comment by irowbin** [comment] 2017-07-05 10:24
So how and where do we add that location?  Any sample for that too? Thanks.

**Comment by DmitrySikorsky** [comment] 2017-07-05 10:37
I will think about that.

**Comment by Xarkam** [comment] 2018-01-05 08:09
Hello,

I did not pay attention to this issue.
I also needed to be able to load files dynamically out of the assemblies.

I simply added a line in program.cs to define a folder where to find the elements.

https://github.com/SOFTINUX/Base/blob/feature/security_extension/WebApplication/Program.cs#L19

Everything in wwwroot will be loaded dynamically

**Comment by DmitrySikorsky** [comment] 2018-01-05 10:59
Content of the wwwroot works without any special code. The issue is that the styles/scripts inside the extension projects needs to be rebuild in order the changes to be applied, because they are added as resources.

So for the development time it would be good to make it possible to include such folders as regular file system static content.

But it is not so easy, because at the same time we should turn off such content from being discovered from the assemblies, because in this way we can have the same static content to be discovered from the file system AND the assemblies at the same time.

So I think we should make it possible manually fix this task by calling method like

ExcludeAssemblyFromStaticContentDiscroveringAndIncludeStaticContentFromPath(assembly, path)

Something like this.

**Comment by irowbin** [comment] 2018-01-05 15:40
@DmitrySikorsky  Man!!! that's mouthful word to say though; haha 😆 🤣 😆 🤣

**Comment by DmitrySikorsky** [comment] 2018-01-05 15:44
:) that was a joke. Of course that method name is too short for the serious work ;)

**Comment by LucaGabi** [comment] 2018-11-30 10:34
Any updates on this ?

**Comment by DmitrySikorsky** [comment] 2018-12-29 09:36
@LucaGabi not yet, but I will fix this ASAP.

**Comment by DmitrySikorsky** [comment] 2019-08-08 12:00
So, I'm thinking about more flexible resource providing in 5.0.0. I'm closing this issue and will create a new one which we will be able to discuss.

**Closed by DmitrySikorsky** 2019-08-08 12:00 UTC
Labels: question
