### ISSUE TITLE
Suggestion: use Path separator in extensions path

### ISSUE THREAD

**Issue by Xarkam** [ExtCore/ExtCore#95] opened 2017-11-08 10:40 UTC
Why not using `Path.DirectorySeparatorChar` to dynamically replace "/" or "\\" characters, in GetAssembliesFromPath instead of changing every time in appsettings.json ? See your code here [DefaultAssemblyProvider.cs#L79](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.WebApplication/DefaultAssemblyProvider.cs#L79) and our code [Startup.cs#L26](https://github.com/SOFTINUX/Base/blob/feature/security_extension/WebApplication/Startup.cs#L26)

**Comment by DmitrySikorsky** [comment] 2017-11-08 10:51
I think it is good idea, but it is breaking change, so we will be able to implement it in future major release. But, what about the connection string? User will still have to specify different paths for different OS, if db file location is not application root one. So maybe we should check the paths and replace wrong path separators automatically... Not sure.

**Comment by postb99** [comment] 2017-11-08 10:58
What would it break?
We typically develop the same project with Windows and Linux machines thus our change proposal.
But we rely only on one configuration file. Though, the idea is valuable for every configuration file the application would pick and use (need to think how to handle this case).

**Comment by DmitrySikorsky** [comment] 2017-11-14 13:53
I mean, that if you have /Some/Path in your configuration file, and if we change this logic, your application will stop working until you fix your config. That's why it is breaking change.

BTW. We can just write paths in Linux format. Windows will understand them! So maybe this is the best option? Just to write /Some/Path, instead of \Some\Path.

**Comment by DmitrySikorsky** [comment] 2017-11-14 13:55
...But maybe @Xarkam is right, we can just replace all the / and \ in the paths with Path.DirectorySeparatorChar, so it will work and it won't be important what path separators are used.

**Comment by DmitrySikorsky** [comment] 2017-11-14 21:24
So, I decided to have the paths as /, so it works on all the platforms (have tested today on Windows and Ubuntu Linux).

**Comment by postb99** [comment] 2017-11-15 05:50
This solves the issue on any platform and cross platform development, nicely.

**Comment by DmitrySikorsky** [comment] 2018-10-17 21:21
It seems that the issue is fixed, so I close it for now.

**Closed by DmitrySikorsky** 2018-10-17 21:21 UTC
Labels: question
