### ISSUE TITLE
Fail to debug the sample project.

### ISSUE THREAD

**Issue by irowbin** [ExtCore/ExtCore#41] opened 2017-01-01 15:04 UTC
Can't debug the sample app. Please need help. Build and run successfully but never hit to the debug break point. Thanks

**Comment by DmitrySikorsky** [comment] 2017-01-01 22:03
Hi! Add direct dependencies on your extension projects to the host application and you will be able to debug them. Use dlls copying only for fully fixed extensions.

**Comment by irowbin** [comment] 2017-01-02 12:07
Thank You. I will try again and let you know.

**Comment by DmitrySikorsky** [comment] 2017-01-10 23:03
I think the issue is fixed, so I close it for now. Feel free to reopen it if have questions.

**Closed by DmitrySikorsky** 2017-01-10 23:03 UTC

**Comment by Jantje2000** [comment] 2020-02-15 07:45
Hi, I'm sorry that I should ask this, but what do you mean with adding a reference from the extension project to the host project?

When I build my extension project (It's a class library type), i get an extension.dll file. If I add an reference to that file, I can't debug however.

What am I doing wrong?

**Comment by DmitrySikorsky** [comment] 2020-03-09 17:21
Just add a direct project reference on your extension project to the main (host) web app while development. You will be able to debug it as any other normal project. And when it is done remove the reference and load it as a DLL file.
